version: "3.7"

services:
  db:
    environment:
      - POSTGRES_USER=postgres
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
